---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dladuke1/public_html/sullivan/csc364/
    - /bin/cp -R index.php $DEPLOYPATH
    - /bin/cp -R header.php $DEPLOYPATH
    - /bin/cp -R footer.php $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
